name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          echo "Build completed. Listing target directory contents:"
          ls -la target/

      - name: Extract release notes
        run: |
          echo "## What's Changed" > RELEASE_NOTES.md
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 $(git describe --tags --abbrev=0)^ 2>/dev/null || git rev-list --max-parents=0 HEAD)..$(git describe --tags --abbrev=0) >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: uiTools-jar
          path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: uiTools-jar

      - name: List downloaded files
        run: |
          echo "Listing current directory contents:"
          ls -la
          echo "Checking for JAR files:"
          ls -la *.jar

      - name: Extract release notes
        run: |
          echo "## What's Changed" > RELEASE_NOTES.md
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 $(git describe --tags --abbrev=0)^ 2>/dev/null || git rev-list --max-parents=0 HEAD)..$(git describe --tags --abbrev=0) >> RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md

      - name: Create Release
        run: |
          echo "Creating release with the following JAR files:"
          ls -la *.jar
          JAR_FILE=$(ls *.jar | head -n 1)
          echo "Using JAR file: $JAR_FILE"
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes-file RELEASE_NOTES.md \
            ${{ contains(github.ref, '-') && '--prerelease' || '' }} \
            $JAR_FILE#uiTools-${{ github.ref_name }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}